# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: '10.1.0'

    steps:
      - checkout

      - run:
          # build our application
          name: Build Application
          command: xcodebuild

      - run:
          name: Sign Application
          command: |
            base64 --help
            echo ${DEV_CERT} | base64 -D -i - -o developer-cert.p12
            security import developer-cert.p12 -P ${DEV_CERT_PWD}
            codesign -f -s "Mac Developer: tompahoward@gmail.com (4BDJKDUR27)" build/Release/Mobile\ Router\ Status.app

      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r Mobile-Router-Status.zip build/Release/Mobile\ Router\ Status.app
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      # - store_test_results:
      #     path: test_output/report.xml
      - store_artifacts:
          path: Mobile-Router-Status.zip
          destination: applicaton
